--- 
abstract: Norwegian subclass of Number::Phone
author: Andreas Marienborg  C<< <andreas@startsiden.no> >>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Number-Phone-NO
no_index: 
  directory: 
    - inc
    - t
requires: 
  Carp: 0
  DBM::Deep: 0
  Number::Phone: 0
  Scalar::Util: 0
version: 0.05
